name: idevol_dash
proxy:
  dash:
    - dash.lndo.site
services:
  dash:
    type: php:8.3
    composer_version: 2
    via: apache:2.4
    ssl: false
    ports:
      - 8000:80
      - 5173:5173 # Vite HTTP service development port
      - 9003:9003 # Xdebug port
    xdebug: debug
    build_as_root:
      - . /app/lando/scripts/01-setup-php-extensions.sh
      - . /app/lando/scripts/02-install-node.sh
    config:
      php: lando/config/php/php.ini
      vhosts: lando/config/apache/vhosts.conf
events:
  post-start:
    - dash: . /app/lando/scripts/03-verify-development-environment.sh
    - dash: . /app/lando/scripts/04-setup-env-files.sh
    - dash: . /app/lando/scripts/05-api-install-composer-dependencies.sh
    - dash: . /app/lando/scripts/06-frontend-dependencies-install.sh
    - dash: . /app/lando/scripts/07-frontend-build.sh
tooling:
  printenv:
    service: dash
  php:
    service: dash
    dir: /app/api
  composer:
    service: dash
    dir: /app/api
  node:
    service: dash
    dir: /app/web
  npm:
    service: dash
    dir: /app/web
  npx:
    service: dash
    dir: /app/web
  front-dev:
    service: dash
    dir: /app/web
    cmd:
      - npm run dev
  front-build:
    service: dash
    dir: /app/web
    cmd:
      - npm run build
