name: idevol_dash
proxy:
  dash:
    - dash.lndo.site
services:
  dash:
    type: php:8.3
    composer_version: 2
    via: apache:2.4
    ssl: false
    ports:
      - 8000:80
      - 5173:5173 # Vite HTTP service development port
      - 9003:9003 # Xdebug port
    xdebug: debug
    build_as_root:
      - . /app/lando/scripts/xdebug-setup.sh
      # Note that you will want to use the script for the major version of node you want to install
      # See: https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions
      - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs
      - . /app/lando/scripts/dependencies-install.sh
    config:
      php: lando/config/php/php.ini
      vhosts: lando/config/apache/vhosts.conf
events:
  post-start:
    #- dash: . /app/lando/scripts/setup-env-files.sh
    - dash: . /app/lando/scripts/frontend-build.sh
tooling:
  printenv:
    service: dash
  php:
    service: dash
  composer:
    service: dash
  node:
    service: dash
  npm:
    service: dash
  npx:
    service: dash
  front-dev:
    service: dash
    dir: /app/web
    cmd:
      - npm run dev
  front-build:
    service: dash
    dir: /app/web
    cmd:
      - npm run build
